server.port=${PORT:8080}

bfhl.user.full-name=${BFHL_USER_FULL_NAME:akshay kumar sood}
bfhl.user.email=${BFHL_USER_EMAIL:akshay1051.be23@chitkarauniversity.edu.in}
bfhl.user.roll-number=${BFHL_USER_ROLL_NUMBER:2311981051}
bfhl.user.date-of-birth=${BFHL_USER_DATE_OF_BIRTH:23-12-2004}
